### ISSUE TITLE
pycryptodome 依赖的一个小问题

### ISSUE THREAD

**Issue by tylinux** [lupohan44/PyCookieCloud#2]
一个小问题，环境 macOS， 执行时提示找不到  `Cryptodome` ，原因是依赖的 pycryptodome 是覆盖安装到 PyCrypto 的目录下的，所以 import 的时候应该是 `from Crypto`。要使用 `from Cryptodome import`，应该依赖 `pycryptodomex`，多个 `x`。来源：https://pycryptodome.readthedocs.io/en/latest/src/installation.html。

**Comment by lupohan44** [comment]
由于没有mac设备 是否可以提一个PR呢
