### ISSUE TITLE
请问 UUID 在哪里获取啊？是插件里的用户 key 嘛？输入 UUID 显示 fail get key。

### ISSUE THREAD

**Issue by xushier** [lupohan44/PyCookieCloud#4]
请问 UUID 在哪里获取啊？是插件里的用户 key 嘛？输入 UUID 显示 fail get key。

**Comment by lupohan44** [comment]
用户KEY就是UUID
这个库在任何情况下都不会输出fail get key, 请自行确认这个输出是哪里显示的

**Comment by xushier** [comment]
这里
![image](https://github.com/lupohan44/PyCookieCloud/assets/31540107/7264c859-721a-42ea-bf09-a1099f12d6ae)

**Comment by lupohan44** [comment]
> 这里 ![image](https://private-user-images.githubusercontent.com/31540107/301049355-7264c859-721a-42ea-bf09-a1099f12d6ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2Nzk0MDksIm5iZiI6MTcwNjY3OTEwOSwicGF0aCI6Ii8zMTU0MDEwNy8zMDEwNDkzNTUtNzI2NGM4NTktNzIxYS00MmVhLWJmMDktYTEwOTlmMTJkNmFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDA1MzE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5MWI5YzcyMGMwNzcwNzM5OWQxNzZlODA2ZGYwOGQ3NGFiNDYwNmUzMGI5NjRmZWRmMzU1NWQ4YTI2ZmExNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PeNX7Zy5ZW1cSX7kmfL05eWDP2k_29lMuFTiEuG8SdQ)

这个是示例代码... 你3个参数都有正确填写吗?

**Comment by xushier** [comment]
都填了

**Comment by xushier** [comment]
直接从插件上拷贝过来的

**Comment by lupohan44** [comment]
插件是否已经上传过cookies了?

**Comment by xushier** [comment]
上传过了，插件是上传模式

**Comment by lupohan44** [comment]
等等 你是the_key报错?

**Comment by xushier** [comment]
现在又显示未获取到加密数据了
None
Failed to get encrypted data
[Finished in 384ms]

**Comment by xushier** [comment]
![image](https://github.com/lupohan44/PyCookieCloud/assets/31540107/c0e8bef2-8e5d-441c-a181-1efa68e5bdb4)

**Comment by lupohan44** [comment]
你可以先使用postman等接口调试工具测试直接访问接口是否能取得数据

**Comment by xushier** [comment]
是可以的
![image](https://github.com/lupohan44/PyCookieCloud/assets/31540107/d6428a4d-2bfd-4ae1-99dd-083f7d22e396)

**Comment by lupohan44** [comment]
从你打码的图片里, 我发现了你域名后面有跟路径/ck 你代码里面填的链接路径ck后面没有添加斜线 / 
代码里面是对链接使用urljoin
```
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib.parse import urljoin
>>> urljoin('https://test.com/test', 'test/test1')
'https://test.com/test/test1'
>>> urljoin('https://test.com/test/', 'test/test1')
'https://test.com/test/test/test1'
```
缺少最后面的斜线导致拼接出来的链接是错误的, 感觉urljoin的拼接做法不太合理, 应该要拼出来正确的结果, 但是urljoin出来的结果是这样, 所以你只能在你代码的链接里最后面加上斜线

**Comment by xushier** [comment]
貌似还是不行
![image](https://github.com/lupohan44/PyCookieCloud/assets/31540107/3c6b4c7d-f62b-460f-99f1-07189efbd2ed)

**Comment by xushier** [comment]
如果自己在浏览器调试获取解密的数据，链接是什么样的。插件的描述没看懂。是https://domain.com/ck/get/uuid?password=pwd吗
![image](https://github.com/lupohan44/PyCookieCloud/assets/31540107/893f06c6-e8ff-4d69-ad6b-0455825cd4d4)

**Comment by lupohan44** [comment]
这样的话你可能要看一下每个请求返回的结果了

**Comment by lupohan44** [comment]
> 如果自己在浏览器调试获取解密的数据，链接是什么样的。插件的描述没看懂。是[https://domain.com/ck/get/uuid?password=pwd吗](https://domain.com/ck/get/uuid?password=pwd%E5%90%97) ![image](https://private-user-images.githubusercontent.com/31540107/301052508-893f06c6-e8ff-4d69-ad6b-0455825cd4d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2ODAzNDIsIm5iZiI6MTcwNjY4MDA0MiwicGF0aCI6Ii8zMTU0MDEwNy8zMDEwNTI1MDgtODkzZjA2YzYtZThmZi00ZDY5LWFkNmItMDQ1NTgyNWNkNGQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDA1NDcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhZjg0MzUwM2NkYmIzY2QzYjUwMDIwMGM0NzVhOWI1NTExNjg0ZWEwM2FlZTdkNTNkOTkxOGQ1ZGFhZmVhMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pyhZGX_T_RKeygOh4AtNOY4IDw1uEL7svxJFz5qJxH8)

是的 但是为了安全 我这边是不会发送password到后端 是使用没password获取到加密后的结果后在python这边进行解密

**Comment by xushier** [comment]
可以了。是代理原因导致的ssl错误，所以第一步 check_connection() 验证不通过

**Comment by xushier** [comment]
谢谢！

**Comment by loracc802** [comment]
> 可以了。是代理原因导致的ssl错误，所以第一步 check_connection() 验证不通过

请问是如何解决的，我也碰到了这个问题

**Comment by lupohan44** [comment]
> > 可以了。是代理原因导致的ssl错误，所以第一步 check_connection() 验证不通过
> 
> 请问是如何解决的，我也碰到了这个问题

禁用SSL或者使用其他代理
